export const TAG_ICONS: Record<string, string> = {
  VEGAN: "🌱",
  VEGETARIAN: "🥦🥕",
  GLUTEN_FREE: "🚫🌾",
  BREAKFAST: "🍳🥞",
  LUNCH: "🥪🍱",
  DINNER: "🍽️🍝",
  DESSERT: "🍰🍨",
  THAI: "🇹🇭",
  INDIAN: "🇮🇳",
  MEXICAN: "🇲🇽",
  VIETNAMESE: "🇻🇳",
  MIDDLE_EASTERN: "🧆🥙",
  SPANISH: "🇪🇸",
  AMERICAN: "🇺🇸",
  ITALIAN: "🇮🇹",
  CHINESE: "🇨🇳",
  COLOMBIAN: "🇨🇴",
  JAPANESE: "🇯🇵",
  COMFORT: "🍲",
  HEALTHY: "🥗💚",
};
